/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kcc_sorg_android_jni_cpp_People */

#ifndef _Included_kcc_sorg_android_jni_cpp_People
#define _Included_kcc_sorg_android_jni_cpp_People
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kcc_sorg_android_jni_cpp_People
 * Method:    printPeople
 * Signature: (Lkcc/sorg/android_jni_cpp/People;)I
 */
JNIEXPORT jint JNICALL Java_kcc_sorg_android_1jni_1cpp_People_printPeople
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
